name: Build

on:
  push:
    branches:
      - master  # 触发条件可以根据你的需求进行调整

jobs:
  build:
    permissions:
      contents: write # Allows this job to create releases
      
    strategy:
      fail-fast: true
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # 拉取代码

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.10.0'  # 选择 Node.js 版本

    - name: corepack enable
      run: corepack enable

    - name: Update yarn # 更新yarn
      run: yarn set version stable

    - name: set nodeLinker # 设置yarn使用node-modules
      run: yarn config set nodeLinker node-modules

    - name: Install dependencies
      run: yarn install  # 安装项目依赖

    - name: Build application
      run: yarn dist # 编译应用程序

    - name: Upload DMG artifact
      uses: actions/upload-artifact@v2
      with:
        name: 鼎小夏-${{ matrix.os }}
        path: dist  # 替换成你的 .dmg 文件路径
